FROM node:13.12.0-alpine3.10 as build
WORKDIR /usr/src/app
COPY package.json yarn.lock ./
RUN yarn install
COPY . .
RUN ls
RUN yarn build --configuration=local

FROM nginx:latest
COPY --from=build /usr/src/app/dist/pickup/ /usr/share/nginx/html/dist/pickup
RUN ls /usr/share/nginx/html
COPY --from=build /usr/src/app/nginx.conf /etc/nginx/conf.d/default.conf
