import { Reservation } from './reservation';

export const RESERVATIONS: Reservation[] = [
    {name: 'Thadchet Kittichotikul',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex'},
     {name: 'Thadchet Kittichotikul',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex'},
     {name: 'Thadchet Kittichotikul',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex'},
     {name: 'Thadchet Kittichotikul',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex'},
     {name: 'Thadchet Kittichotikul',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex'},
     {name: 'Thadchet Kittichotikul',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex'},
     {name: 'Thadchet Kittichotikul',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex'},
     {name: 'Thadchet Kittichotikul',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex'}
  ];