import { Reservation } from './reservation';

export const RESERVATIONS: Reservation[] = [
    {name: 'Thadchet Kittichotikul',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex',
     image: "../../assets/images/bosskung.jpg"},
     {name: 'Thanakorn Pisanoophumi',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex',
     image: "../../assets/images/tiger.jpg"},
     {name: 'Kasidis Pakulanon',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex',
     image: "../../assets/images/boom.jpg"},
     {name: 'Thuantham Jitphakdee',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex',
     image: "../../assets/images/namo.jpg"},
     {name: 'Phatit Sriburi',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex',
     image: "../../assets/images/park.jpg"},
     {name: 'Thanit Tatiwannarat',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex',
     image: "../../assets/images/too.jpg"},
     {name: 'Wutipong Thabsuwan',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex',
     image: "../../assets/images/wut.jpg"},
     {name: 'Thadchet Kittichotikul',
     type: 'Sport',
     model: 'BMW I8',
     reserve_time: '19/1/2020',
     pickup_date: '18/2/2020',
     return_date: '18/3/2020',
     pickup_location: 'Larngear',
     return_location: 'CU Sport Complex',
     image: "../../assets/images/bosskung.jpg"}
  ];